### PR TITLE
Update to current APIs

### PR DESCRIPTION
**Pull request by darko-mijic**

### CODE REVIEW

**Comment by darko-mijic** [comment]
@DominikGuzei, @rhyslbw: I need your help with this

**Comment by DominikGuzei** [comment]
@darko-mijic what is the problem?

**Comment by darko-mijic** [comment]
We need to update ES to latest changes to messaging and domain. `Space.domain.Command`, `Space.domain.Event`.

**Comment by rhyslbw** [comment]
I can do this

**Comment by rhyslbw** [comment]
@darko-mijic ready for review and merge

**Pull request merged**
