### PR TITLE
Fix/wrong snapshot versions

### PR DESCRIPTION
**Pull request by DominikGuzei**
This PR fixes wrong snapshot versions – by bumping the aggregate version after successful commit but before snapshotting.

### CODE REVIEW

**Comment by darko-mijic** [comment]
I can confirm that this fixes the issue with snapshotting.

**Comment by darko-mijic** [comment]
BTW we don't have this covered with tests. All tests where green before this fix.

**Comment by DominikGuzei** [comment]
Yep that's true – i will setup a test for the repository.

**Comment by darko-mijic** [comment]
:+1:

**Comment by DominikGuzei** [comment]
@darko-mijic added integration tests – you can verify it's working by commenting out this line:
https://github.com/meteor-space/event-sourcing/blob/fix/wrong-snapshot-versions/source/server/infrastructure/repository.coffee#L31

**Comment by darko-mijic** [comment]
Thanks Dominik. I can verify that test and fix are working correctly. This can be merged.

**Comment by DominikGuzei** [comment]
Go for it! :+1:
Merging own PRs should be a rare exception :wink:

**Pull request merged**
